from roman_funcs import *

print(to_roman(10))
def test_romanos_simples():
    assert to_roman(1) == 'I'
    assert to_roman(2) == 'II'
    assert to_roman(3) == 'III'
    assert to_roman(4) == 'IV'
    assert to_roman(5) == 'V'
    assert to_roman(6) == 'VI'
    assert to_roman(7) == 'VII'
    assert to_roman(8) == 'VIII'
    assert to_roman(9) == 'IX'
    assert to_roman(10) == 'X' 
    assert to_roman(20) == 'XX'
    assert to_roman(30) == 'XXX'
    assert to_roman(40) == 'XL'
    assert to_roman(50) == 'L'
    assert to_roman(60) == 'LX'
    assert to_roman(70) == 'LXX'
    assert to_roman(80) == 'LXXX'
    assert to_roman(90) == 'XC' 

    assert to_roman(100) == 'C' 
    assert to_roman(200) == 'CC'
    assert to_roman(300) == 'CCC'
    assert to_roman(400) == 'CD'
    assert to_roman(500) == 'D'
    assert to_roman(600) == 'DC'
    assert to_roman(700) == 'DCC'
    assert to_roman(800) == 'DCCC'
    assert to_roman(900) == 'CM' 

    assert to_roman(58) == 'LVIII' 
    assert to_roman(1994) == 'MCMXCIV' 
    assert to_roman(3999) == 'MMMCMXCIX' 
    assert to_roman(723) == 'DCCXXIII' 
    assert to_roman(79) == 'LXXIX' 
    assert to_roman(999) == 'CMXCIX'

